permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: "id_token"
          workload_identity_provider: "projects/202129374367/locations/global/workloadIdentityPools/github-pool/providers/gitworkexp"
          service_account: "github-deployer@tw-gits-backstage-sandbox-02ad.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ...
