name: GCP OIDC Auth Test

on:
  push:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  auth-gcp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: "id_token"
          workload_identity_provider: "projects/202129374367/locations/global/workloadIdentityPools/gitworkexp/providers/gitworkexp"
          service_account: "github-deployer@tw-gits-backstage-sandbox-02ad.iam.gserviceaccount.com"
          audience: sts.googleapis.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: tw-gits-backstage-sandbox-02ad

      - name: Test gcloud authentication
        run: |
          gcloud auth list
          gcloud projects list
